<a href="https://colab.research.google.com/github/UmaibaFasal/learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [6]:
#please provide your answer below this line.
import numpy as np
a=np.random.randint(10,size=(3,3))
print(a)
b=np.random.randint(10, size=(3,3))
print(b)
D=np.dot(a,b)
print("\nDOT PRODUCT")
print(D)
print("\nTRANSPOSE")
print(np.transpose(D))


[[1 6 4]
 [5 1 8]
 [3 7 3]]
[[2 1 4]
 [3 7 8]
 [5 0 9]]

DOT PRODUCT
[[ 40  43  88]
 [ 53  12 100]
 [ 42  52  95]]

TRANSPOSE
[[ 40  53  42]
 [ 43  12  52]
 [ 88 100  95]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [16]:
#please provide your answer below this line.
import numpy as np
a=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(a)
print("\nDETERMINANT")
print(np.linalg.det(a))


[[55 25 15]
 [30 44  2]
 [11 45 77]]

DETERMINANT
137180.0000000001
