<a href="https://colab.research.google.com/github/UmaibaFasal/learn.py/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [2]:
#please type your answer below this line.
import numpy as np
a=np.random.randint(low=0, high=8, size=(3,3))
b=np.random.randint(low=10, high=19, size=(3,3))
print(a)
print(b)
print("\nOUTER PRODUCT\n")
print(np.outer(a,b,out=None))
print("\nDOT PRODUCT\n")
print(np.dot(a,b,out=None))
print("\nELEMENT WISE PRODUCT\n")
print(np.multiply(a,b))


[[0 2 2]
 [6 4 7]
 [6 4 2]]
[[16 13 17]
 [11 18 16]
 [13 17 17]]

OUTER PRODUCT

[[  0   0   0   0   0   0   0   0   0]
 [ 32  26  34  22  36  32  26  34  34]
 [ 32  26  34  22  36  32  26  34  34]
 [ 96  78 102  66 108  96  78 102 102]
 [ 64  52  68  44  72  64  52  68  68]
 [112  91 119  77 126 112  91 119 119]
 [ 96  78 102  66 108  96  78 102 102]
 [ 64  52  68  44  72  64  52  68  68]
 [ 32  26  34  22  36  32  26  34  34]]

DOT PRODUCT

[[ 48  70  66]
 [231 269 285]
 [166 184 200]]

ELEMENT WISE PRODUCT

[[  0  26  34]
 [ 66  72 112]
 [ 78  68  34]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [4]:
#please type your answer below this line.
import numpy as np
a=np.random.randint(low=0, high=16, size=(4,4))
b=np.array([1, 2,3,4])
print(a)
s=a+4
print("\nADDITION\n")
print(s)
c=a*b
print("\nMULTIPICATION\n")
print(c)


[[11  2 13  2]
 [ 8  5  4  9]
 [ 9 15 12  9]
 [11 14  7  4]]

ADDITION

[[15  6 17  6]
 [12  9  8 13]
 [13 19 16 13]
 [15 18 11  8]]

MULTIPICATION

[[11  4 39  8]
 [ 8 10 12 36]
 [ 9 30 36 36]
 [11 28 21 16]]
