<a href="https://colab.research.google.com/github/UmaibaFasal/learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
import numpy as np
a=np.random.randint(10,size=(3,3))
print(a)

[[2 2 7]
 [1 3 0]
 [5 2 7]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [1]:
#please provide your answer below this line.
import numpy as np
a=np.random.randint(10,size=(4,4))
print("array1:")
print(a)
b=np.random.randint(10,size=(4,4))
print("array2:")
print(b)
A=a.reshape(2,8)
B=b.reshape(2,8)
print("vertically stacked:")
print(np.vstack((A,B)))
print("horizontally stacked")
print(np.hstack((A,B)))

array1:
[[7 8 9 9]
 [2 1 6 8]
 [8 9 5 5]
 [0 5 5 4]]
array2:
[[0 3 6 2]
 [5 9 8 9]
 [7 6 9 5]
 [1 6 4 0]]
vertically stacked:
[[7 8 9 9 2 1 6 8]
 [8 9 5 5 0 5 5 4]
 [0 3 6 2 5 9 8 9]
 [7 6 9 5 1 6 4 0]]
horizontally stacked
[[7 8 9 9 2 1 6 8 0 3 6 2 5 9 8 9]
 [8 9 5 5 0 5 5 4 7 6 9 5 1 6 4 0]]
