<a href="https://colab.research.google.com/github/UmaibaFasal/learn.py/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [31]:
#please provide your answer below this line
import numpy as np
a=np.random.randint(15, size=(4,4))
print("HORIZONTAL\n")
print(np.hsplit(a, 4))
print("\nVERTICAL\n")
print(np.vsplit(a,4))

HORIZONTAL

[array([[ 1],
       [ 2],
       [ 8],
       [13]]), array([[ 2],
       [ 8],
       [14],
       [ 1]]), array([[12],
       [ 9],
       [ 6],
       [11]]), array([[ 9],
       [14],
       [ 5],
       [11]])]

VERTICAL

[array([[ 1,  2, 12,  9]]), array([[ 2,  8,  9, 14]]), array([[ 8, 14,  6,  5]]), array([[13,  1, 11, 11]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [33]:
#please provide your answer below this line
import numpy as np
a=np.random.rand(3,3)
print(a)
print("\nCEIL")
print(np.ceil(a))
print("\nFLOOR")
print(np.floor(a))

[[0.64936325 0.22072524 0.05104628]
 [0.57033808 0.20406527 0.8169621 ]
 [0.77900194 0.90038847 0.5739356 ]]

CEIL
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

FLOOR
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [34]:
#please provide your answer below this line.
import numpy as np
a=np.random.rand(1,4)
print(a)
print(a.shape)
print("\nSQUEEZED ARRAY")
A=(np.squeeze(a, axis=0))
print(A)
print(A.shape)
print("\nEXPANDED ARRAY")
E=(np.expand_dims(a, axis=0))
print(E)
print(E.shape)

[[0.47291    0.49689908 0.73930664 0.03200291]]
(1, 4)

SQUEEZED ARRAY
[0.47291    0.49689908 0.73930664 0.03200291]
(4,)

EXPANDED ARRAY
[[[0.47291    0.49689908 0.73930664 0.03200291]]]
(1, 1, 4)
