<a href="https://colab.research.google.com/github/UmaibaFasal/learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [ ]:
#please type your answer below this line.
import numpy as np
a=np.random.randint(low=0, high=15, size=(4,4))
print(a)
print("\ntrace=",np.trace(a))

[[ 7  3  6  0]
 [10  7  2 12]
 [ 0  2  7  8]
 [ 9  8 11  8]]
trace= 29


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [ ]:
#please type your answer below this line.
import numpy as np
a=np.array(([6,1,1],[4,-2,5],[2,8,7]))
print(a)  
print("\nINVERSE\n",np.linalg.inv(a))


[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

INVERSE
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [ ]:
#please type your answer below this line.
import numpy as np
a=np.random.randint(low=0, high=8, size=(3,3))
print(a)
print("\nNORM=",np.linalg.norm(a))

[[0 0 0]
 [1 2 1]
 [3 7 5]]

NORM= 9.433981132056603


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [ ]:
#please type your answer below this line.
import numpy as np
a=np.random.randint(low=0,high=15, size=(4,4))
print(a)
print("\nEIGEN VALUES AND EIGEN VECTORS\n",np.linalg.eigh(a))

[[ 9  4  1  0]
 [11  6  7  6]
 [ 1 11  8 14]
 [13 10  1 14]]

EIGEN VALUES AND EIGEN VECTORS
 (array([-8.00719549, -1.41845024, 11.82856777, 34.59707797]), array([[-0.39681628,  0.6948226 ,  0.25675349, -0.54206646],
       [ 0.76668598,  0.15813649, -0.34137205, -0.52024089],
       [-0.49635864, -0.18665813, -0.80748386, -0.25837311],
       [-0.09141962, -0.67629369,  0.40683239, -0.60725342]]))
